# Form implementation generated from reading ui file 'c:\Users\riscyseven\TeleScore\build\exe.win-amd64-3.11\lib\src\component\teamcomp\teamcomp.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(175, 163)
        Form.setStyleSheet("QWidget {\n"
"    background-color: #242325;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #808080;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: #4357AD;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    background-color: #213aa6;\n"
"    color: white;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon_pushButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_pushButton.sizePolicy().hasHeightForWidth())
        self.icon_pushButton.setSizePolicy(sizePolicy)
        self.icon_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.icon_pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.icon_pushButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.icon_pushButton.setAutoFillBackground(False)
        self.icon_pushButton.setStyleSheet("")
        self.icon_pushButton.setObjectName("icon_pushButton")
        self.verticalLayout.addWidget(self.icon_pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.nameLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.nameLineEdit.setFrame(False)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout_2.addWidget(self.nameLineEdit)
        self.attrLineEdit = QtWidgets.QLineEdit(parent=Form)
        self.attrLineEdit.setFrame(False)
        self.attrLineEdit.setObjectName("attrLineEdit")
        self.verticalLayout_2.addWidget(self.attrLineEdit)
        self.setteam_PushButton = QtWidgets.QPushButton(parent=Form)
        self.setteam_PushButton.setStyleSheet("")
        self.setteam_PushButton.setFlat(False)
        self.setteam_PushButton.setObjectName("setteam_PushButton")
        self.verticalLayout_2.addWidget(self.setteam_PushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.icon_pushButton.setText(_translate("Form", "Set Logo"))
        self.nameLineEdit.setPlaceholderText(_translate("Form", "Name"))
        self.attrLineEdit.setPlaceholderText(_translate("Form", "Attribute"))
        self.setteam_PushButton.setText(_translate("Form", "Set Team"))
