# Form implementation generated from reading ui file 'c:\Users\riscyseven\TeleScore\build\exe.win-amd64-3.11\lib\src\editor\activetab.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_yay(object):
    def setupUi(self, yay):
        yay.setObjectName("yay")
        yay.resize(300, 284)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(yay.sizePolicy().hasHeightForWidth())
        yay.setSizePolicy(sizePolicy)
        yay.setMinimumSize(QtCore.QSize(300, 0))
        self.gridLayout = QtWidgets.QGridLayout(yay)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(parent=yay)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=yay)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(parent=yay)
        self.treeWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.treeWidget.setProperty("showDropIndicator", False)
        self.treeWidget.setDragEnabled(False)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.treeWidget.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setIndentation(0)
        self.treeWidget.setItemsExpandable(False)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 1, 0, 1, 2)

        self.retranslateUi(yay)
        QtCore.QMetaObject.connectSlotsByName(yay)

    def retranslateUi(self, yay):
        _translate = QtCore.QCoreApplication.translate
        yay.setWindowTitle(_translate("yay", "Form"))
        self.pushButton.setText(_translate("yay", "Current Tab"))
        self.pushButton_2.setText(_translate("yay", "All Tab"))
        self.treeWidget.headerItem().setText(0, _translate("yay", "Component"))
