# Form implementation generated from reading ui file 'c:\Users\riscyseven\TeleScore\build\exe.win-amd64-3.11\lib\src\editor\conntab\hotkeyman.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(393, 57)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.keySequenceEdit = QtWidgets.QKeySequenceEdit(parent=Form)
        self.keySequenceEdit.setObjectName("keySequenceEdit")
        self.gridLayout.addWidget(self.keySequenceEdit, 0, 0, 1, 1)
        self.clear_pushButton = QtWidgets.QPushButton(parent=Form)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout.addWidget(self.clear_pushButton, 0, 2, 1, 1)
        self.submit_pushButton = QtWidgets.QPushButton(parent=Form)
        self.submit_pushButton.setObjectName("submit_pushButton")
        self.gridLayout.addWidget(self.submit_pushButton, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.clear_pushButton.setText(_translate("Form", "Clear"))
        self.submit_pushButton.setText(_translate("Form", "Submit"))
