# Form implementation generated from reading ui file 'c:\Users\riscyseven\TeleScore\build\exe.win-amd64-3.11\lib\src\component\penalty\penaltycomp.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PenaltyClock(object):
    def setupUi(self, PenaltyClock):
        PenaltyClock.setObjectName("PenaltyClock")
        PenaltyClock.resize(266, 166)
        PenaltyClock.setStyleSheet("QWidget {\n"
"    background-color: #242325;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background-color: #4357AD;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: none;\n"
"    background-color: #213aa6;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color:#202a54;\n"
"    color: gray;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(PenaltyClock)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=PenaltyClock)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 258, 109))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 3, 0, 1, 6)
        self.undo_pushButton = QtWidgets.QPushButton(parent=PenaltyClock)
        self.undo_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.undo_pushButton.sizePolicy().hasHeightForWidth())
        self.undo_pushButton.setSizePolicy(sizePolicy)
        self.undo_pushButton.setMinimumSize(QtCore.QSize(50, 0))
        self.undo_pushButton.setMaximumSize(QtCore.QSize(40, 30))
        self.undo_pushButton.setObjectName("undo_pushButton")
        self.gridLayout.addWidget(self.undo_pushButton, 4, 5, 1, 1)
        self.plyr_lineEdit = QtWidgets.QLineEdit(parent=PenaltyClock)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plyr_lineEdit.setFont(font)
        self.plyr_lineEdit.setStyleSheet("color: white;\n"
"background-color: #808080;\n"
"border: none;")
        self.plyr_lineEdit.setObjectName("plyr_lineEdit")
        self.gridLayout.addWidget(self.plyr_lineEdit, 1, 0, 1, 2)
        self.time_lineEdit = QtWidgets.QLineEdit(parent=PenaltyClock)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_lineEdit.setFont(font)
        self.time_lineEdit.setStyleSheet("color: white;\n"
"background-color: #808080;\n"
"border: none;\n"
"")
        self.time_lineEdit.setInputMask("99:99")
        self.time_lineEdit.setObjectName("time_lineEdit")
        self.gridLayout.addWidget(self.time_lineEdit, 1, 2, 1, 1)
        self.add_pushButton = QtWidgets.QPushButton(parent=PenaltyClock)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_pushButton.sizePolicy().hasHeightForWidth())
        self.add_pushButton.setSizePolicy(sizePolicy)
        self.add_pushButton.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.add_pushButton.setFont(font)
        self.add_pushButton.setObjectName("add_pushButton")
        self.gridLayout.addWidget(self.add_pushButton, 1, 3, 1, 3)

        self.retranslateUi(PenaltyClock)
        QtCore.QMetaObject.connectSlotsByName(PenaltyClock)

    def retranslateUi(self, PenaltyClock):
        _translate = QtCore.QCoreApplication.translate
        PenaltyClock.setWindowTitle(_translate("PenaltyClock", "Form"))
        self.undo_pushButton.setText(_translate("PenaltyClock", "Undo"))
        self.plyr_lineEdit.setPlaceholderText(_translate("PenaltyClock", "Player #"))
        self.time_lineEdit.setText(_translate("PenaltyClock", "00:00"))
        self.add_pushButton.setText(_translate("PenaltyClock", "+"))
